# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id_pub', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nidn', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=1000)),
                ('cite', models.CharField(blank=True, max_length=10)),
                ('authors', models.CharField(max_length=2000)),
                ('keywords', models.CharField(blank=True, max_length=1000)),
                ('abstract', models.CharField(blank=True, max_length=10000)),
                ('year', models.CharField(max_length=4)),
                ('source_title', models.CharField(blank=True, max_length=1000)),
                ('volume', models.CharField(blank=True, max_length=100)),
                ('DOI', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=501)),
            ],
        ),
    ]
