# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-15 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='DOI',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='abstract',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='cite',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='link',
            field=models.CharField(blank=True, max_length=501, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='source_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
