# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20200515_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='authors',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
