# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20200515_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='topik',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
