# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_papers_topik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='topik',
        ),
    ]
