# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_remove_papers_topik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id_publication', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('id_topic', models.CharField(max_length=10)),
            ],
        ),
    ]
