# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('nidn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_univ', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=240)),
                ('education', models.CharField(max_length=256)),
            ],
        ),
    ]
