# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20200515_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='education',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='position',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='scholar_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='sinta_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
